### ISSUE TITLE
Moving UWPHook results in launch error

### ISSUE THREAD

**Issue by kowalski7cc** [BrianLima/UWPHook#10]
When creating a shortcut in steam app should copy itself (or a smaller launcher) in a safe location like %appdata% so moving the downloaded app will not result in a failed launch.

**Comment by BrianLima** [comment]
Sorry for that, will look into a way to fix it.

**Comment by BrianLima** [comment]
If i use a lnk to the app and you move the app it will still cause error because it won't find the .exe it wants and duplicating the app wont be a very inteligente way too. Trying to find another idea.

**Comment by carnageX** [comment]
I don't really see this being a bug.  If you have shortcuts to any other program on Windows, and you move the original program location...your shortcuts will break and you'll have to re-create the shortcuts.
