### ISSUE TITLE
Exporting games is erroring out now

### ISSUE THREAD

**Issue by fr500** [BrianLima/UWPHook#109]
![image](https://user-images.githubusercontent.com/1721040/198675428-b8219164-01c7-4824-969a-c3383c972abc.png)

I get this, afterwards it says games exported succesfully but the games are MIA.

**Comment by fr500** [comment]
Also after that, steam gets an error with steamui.dll, and then when I start steam again, steam downloads it again.

**Comment by fr500** [comment]
Ok I fixed this error by adding the steam api key, but it no longer works, the games do not start

**Comment by fr500** [comment]
I got around to that by setting UWP hook to run as administrator...
Not sure what's going on now.

**Comment by hattabatatta** [comment]
Have the same error and running as admin do not help

**Comment by BrianLima** [comment]
By the stack trace it could be from the image copy to the temporary location, i am still investigating these issues.

**Comment by tycho94** [comment]
Creating the dir yourself fixes the issue

**Comment by AlexByte** [comment]
@tycho94 which folder?

**Comment by hermanho** [comment]
When will have a release with this fixing?
