### ISSUE TITLE
[Suggestion] Embed Resources/DLL's within the app to make it portable

### ISSUE THREAD

**Issue by carnageX** [BrianLima/UWPHook#11]
If you use something like Costura.Fody (https://github.com/Fody/Costura) to embed the resources within the EXE itself, it makes it a self-contained application (slightly bloats the EXE, but then end users don't have to keep track of DLL's if they were to move, update, or delete it).  

Have done this with one of my own WPF apps, and it seemed to work well.

**Comment by BrianLima** [comment]
Right, i will do this for the next release.
