### ISSUE TITLE
Sea of Thieves doesn't show up on the list of installed apps

### ISSUE THREAD

**Issue by EndCod3r** [BrianLima/UWPHook#113]
I've installed Sea of Thieves, I opened UWPHook and I didn't see it, so I tried to restart my PC, yet still not there.
![UWPHook_GHPNgbflqx](https://user-images.githubusercontent.com/73094718/209880622-8ca93b7d-723b-4fd7-8304-767643c6238b.png)

**Comment by SilverDarkBlade** [comment]
none of my games show up either
