### ISSUE TITLE
Flagged by virustotal

### ISSUE THREAD

**Issue by gtrcoi** [BrianLima/UWPHook#115]
https://www.virustotal.com/gui/file/11f318737cbcfac1cda6b0ec062deeea6f5c01cf754408a8e26cce4422a2df87

**Comment by BrianLima** [comment]
Hi, i do not know why it flags the project, but it only flags in 3 very unknown antiviruses. Also, you may read the code and check the files manually with you favorite antivirus. The project is provided as-is, and only runs locally. I've never received other reports.
