### ISSUE TITLE
[Feature Request] Adding other non-Steam games

### ISSUE THREAD

**Issue by Carlmundo** [BrianLima/UWPHook#12]
It would be good if your app was able to detect other non-Steam games, such as Battle.net and Origin, making it a one-stop shop for adding non-Steam games.

Someone has already made a Battle.net launcher (with source code):
https://www.reddit.com/r/Overwatch/comments/3tfrv5/guide_how_to_use_steam_overlay_with_the_blizzard/

**Comment by BrianLima** [comment]
Hi, some people had already suggested that, but it's not on my priority list, i'm more worried about getting Steam Overlay, in-home Streaming and Steam Controller properly working than to add other clients. Not saying i won't, but just that i want to do these things first, hence the name UWPHook.

Thanks for the suggestion.

**Comment by BarterClub** [comment]
Yes. That will be nice as a future feature. But its better to get the overlay working. I would so love this app then. Have you thought about setting up a patreon account?
