### ISSUE TITLE
[BUG] GoW4 starting in Background

### ISSUE THREAD

**Issue by tdmike** [BrianLima/UWPHook#13]
I have been using your program fine with FH3. Yesterday I tried adding GoW4 to my steam list which worked fine, but every time I tried to start it through steam it runs in the background. When started from the start menu it runs fine.

**Comment by BrianLima** [comment]
Could you please try re-adding it? It works fine for other people and the program calls a function to put the Gears window on the foreground. Also check in the options if the streaming mode is enabled.

**Comment by tdmike** [comment]
It only works with streaming mode is disabled, with it enabled it runs in the background.

**Comment by beastlove** [comment]
Hello Brian,

Just wanted to add that I was having the same issue. Also, the performance on the steam is really bad on Gears.

**Comment by BrianLima** [comment]
@beastlove Running the game from Steam and running it normally using the live tiles is giving you guys different performance?

**Comment by BrianLima** [comment]
@tdmike are ou using in-home streaming? that option should only be enabled if that's what you want.

**Comment by beastlove** [comment]
Hi Brian,

It will not launch from the steam link at all. I see the UWPhook program pop up for a second and then I am returned to the game page on the steam link. The same happens when I run the game from the steam client on the host PC. Checking in the task manager I can see Gears of War 4 running but it does not appear on the screen.

The only way I got the game to work was to exit big picture mode on the steam link. Go to the xbox app within windows on launch the game that way. Performance is a bit rubbish doing it this way.

To be fair. I've only had a PC for a few months so I could easily be an idiot.

**Comment by BrianLima** [comment]
@beastlove I don't have a Steam link to test, but from what I tested with in-Home streaming enabling the "streaming mode" in the options on UWPHook should do the trick. Also, performance for streaming might not be perfect because Steam streams the whole desktop in order to stream a UWP game.

**Comment by beastlove** [comment]
@BrianLima I did enable the streaming mode, but that didn't work. Minecraft is the only other game I have and that works OK.

**Comment by BarterClub** [comment]
Im having the same issue with it disabled.

**Comment by Jbbrack03** [comment]
I just wanted to say that I'm also experiencing this issue with GOW4. I've added it correctly to steam. When I launch the game through Steam on the Host PC, it shows the UWPHook screen briefly and then disappears. Nothing else launches. If I open up the Task Manager, it shows Gears of War 4 as a background process. I can't quit Steam until I kill that process. I do have Streaming enabled in UWPHook. My main goal is to be able to stream the game to another PC in my Living Room. Just wanted to jump on and let you guys know that this appears to be an actual bug and not something isolated to a few people. I am running the latest version of Steam and Windows 10 on both computers. I also tried the beta version of Steam and the issue still happened.

**Comment by BrianLima** [comment]
I'm looking further on the issue @Jbbrack03, but i still have no idea what is causing this issue

**Comment by Jbbrack03** [comment]
I appreciate you checking into it. Its got to be something with either Gears Update 2, the latest Windows 10 update, or the latest Steam update. If I leave Streaming turned off in UWPHook, I can see the Gears cursor and hear sound on the remote computer, but no video. I've also reinstalled Gears and Steam. I've tested streaming to two different client PC's. Something is affecting UWPHook's ability to bring Gears to the front with streaming enabled.

**Comment by BrianLima** [comment]
It shows no video because UWPHook must make Steam stream your whole desktop in order to make Streaming work with UWP apps and games. It's just Windows and Steam not talking very well with each other, reinstalling probably won't change anything.

**Comment by Jbbrack03** [comment]
I think we are really close. I tested again with Streaming enabled. I could hear sounds from Gears when I launch the UWPHook shortcut from Steam. If I alt-tab, I can bring it to the front manually. If I try to launch it via Streaming, I get my full desktop from the host PC on the client PC. If I attempt to then bring Gears to the front, the stream freezes and crashes. Hope that this helps.

**Comment by Daywalker442000** [comment]
Having the same issue, if i activate Streaming Mode i only hear sound an no picture and if i switch it off the performance is bad and still cant get the controller to work

**Comment by BrianLima** [comment]
Hi people, I just uploaded a new release, could you please download it, check if streaming mode is enabled and try it again?

@Daywalker442000 @Jbbrack03 @BarterClub  @tdmike @beastlove

**Comment by Jbbrack03** [comment]
Yes! I can confirm that it's now working perfectly for me. I'm also able to use my Steam Controller with the game and it works perfectly. Thank you very much for working on this for us! I was able to get it to stream through my Steambox.

**Comment by BrianLima** [comment]
That's the behavior I found also, the game threats everything as keyboard, Steam now has a Xbox 360 controller configurator, i'll be working with that in the future, i'm glad it also worked for you!

**Comment by Jbbrack03** [comment]
I'm very happy with this working. The Steam Controller is a better controller than the Xbox 360 or Xbox One. The biggest thing that I miss is getting the controller UI in GW4 that you would get if it detected an Xbox Controller. Other than that it's absolutely perfect at this point.
