### ISSUE TITLE
Add a risk alert to the clear shortcuts.vdf button

### ISSUE THREAD

**Issue by Ringeal007** [BrianLima/UWPHook#133]
First of all, let me clarify that my native language is not English. I used a translator to write this issue. If there are any grammar errors in the following text, please forgive me. 

Also, I really like UWPBook software and I am very grateful to the author for creating and maintaining it.

The situation is as follows:

After closing Steam, I am ready to add "Non Steam Games" to my Steam library. But I accidentally clicked the button "Clear shortcuts. vdf", and I didn't know what shortcuts. vdf was for at that time. It wasn't until I opened Steam that I realized all my non Steam games had disappeared.

This button is very dangerous. First of all, it seems to have no purpose description, and there are no risk prompts or user confirmation prompts. Most people may not know the function of this button. With just one click, all "Non Steam Games" in the Steam library will disappear.

I hope the author can add a risk warning to this button, informing users of its function and risks, and allowing them to choose whether to clear the shortcuts.vdf file.

😭Besides, I have lost more than twenty "Non Steam Games". o(TヘTo)

**Comment by BrianLima** [comment]
Added a message confirmation in version 2.14.0

**Comment by Ringeal007** [comment]
> Added a message confirmation in version 2.14.0

I am very excited that you have adopted my issue. Thank you again for creating this software and for your contribution to the player community. (^v^)
