### ISSUE TITLE
Error on steam deck oled

### ISSUE THREAD

**Issue by privetboria** [BrianLima/UWPHook#148]
Hi bro , I've got error after installing on steam deck oled
![Снимок экрана 2024-10-06 033925](https://github.com/user-attachments/assets/eecce834-29eb-45ea-8535-879131f9c363)

**Comment by privetboria** [comment]
I want to add forza 5

**Comment by privetboria** [comment]
my win 11

**Comment by dos-ise** [comment]
This is a duplicate? Do you have the Error Message seen in this thread?

https://github.com/BrianLima/UWPHook/issues/141

**Comment by BrianLima** [comment]
Try the new version https://github.com/BrianLima/UWPHook/releases/tag/2.14.3
