### ISSUE TITLE
Minecraft for Windows without Steam Overlay

### ISSUE THREAD

**Issue by NickTheFox99** [BrianLima/UWPHook#150]
Hi, I used UWPHook to put Minecraft for Windows on Steam.
Launching Minecraft from Steam now works, and Steam recognizes it is open with the "Play" and "Stop" buttons, but the Steam overlay doesn't work properly. Neither the banner or the key combo (Shift+Tab) works. I think this is a problem with UWPHook not recognizing what window Minecraft is using.

**Comment by BrianLima** [comment]
UWPHook can't bind the Steam Overlay to the game.
