### ISSUE TITLE
Error Windows 11 24H2

### ISSUE THREAD

**Issue by JJDizz1L** [BrianLima/UWPHook#151]
Simply does not function.

**Comment by dos-ise** [comment]
This is a duplicate? Die you have the Error Message Seen in this thread?

https://github.com/BrianLima/UWPHook/issues/141

**Comment by BrianLima** [comment]
Hi, i've just pushed a new release, could you please try it? 

https://github.com/BrianLima/UWPHook/releases/tag/2.14.2
