### ISSUE TITLE
[Bug] Access error when launching Gears of War 4

### ISSUE THREAD

**Issue by ThomasHaz** [BrianLima/UWPHook#18]
Launching GoW 4: Standard Edition results in the following error and causes UWPHook to quit/crash.

Error while trying to launch your app.
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

Windows 10 Pro
V. 1709
B. 16299.64

Currently installed on a non boot SSD, though GoW: Ultimate is also on this drive and works. (Though it isn't found by UWPHook: Microsoft.DeltaPC_8wekyb3d8bbwe!App)

![gearserror](https://user-images.githubusercontent.com/9553551/33318959-9b48f9da-d434-11e7-999c-b91b5c65a408.png)

**Comment by BrianLima** [comment]
Not 100% sure, but it seems to be a Windows Store problem, [see this](https://gearsofwar.com/en-us/forums/a35773093fe74d3d9970e0a896b16d6d/threads/0x80070005-windows-store-error-fix/da04e961-2060-4f49-be27-ef5845b57bd2/posts).

Regarding GOW:Ultimate, it is indeed detected, but i just can't get the real name, so it can be found among the "App name not found" section, you can see on the AUMID column, or use the search box to find "Microsoft.DeltaPC".

**Comment by ThomasHaz** [comment]
I looked up the error code, however it was already downloaded and running fine through explorer. I decided to ditch it and download the 119GB app again (I don't know why there is zero compression involved!!) so fingers crossed :)

Regarding GoW:Ultimate, I found it under that list as they have a somewhat recognisable naming convention for their games. I don't know if there is a way you could hard code known IDs that you are unable to extract the correct name from? Feature request perhaps?

**Comment by BrianLima** [comment]
It's bad to hear that, but i can't do many things sadly...

I sure can hardcode some names inside the app, i just have to hope that these apps never change their AUMID when they are updated, also, i don't own Gears of War or some of the other games that didn't list their name, so it becomes a little hard to test these features. 

I'm planning a new release next month, thanks for the suggestion!

**Comment by ThomasHaz** [comment]
One way you could do it would be to have an xml file with the problematic games'/apps' AUMIDs bundled alongside UWPHook, perhaps also with a refresh/update button that will pull the latest file from the GitHub repo. This could be somewhat maintained by the community via pull requests to your repo. 

I would be inclined to keep historic AUMIDs should they change so if somebody hasn't updated their game it is still recognised by UWPHook.

**Comment by m0ngr31** [comment]
I have the same issue with GoW4. Works fine when I launch from explorer
