### ISSUE TITLE
[Question] How to actually open UWPHook?

### ISSUE THREAD

**Issue by cybnz** [BrianLima/UWPHook#21]
I know that sound stupid, but I have no idea how to actually use UWPHook, as there is no EXE or something obvious for me to use.

Sorry.

**Comment by BrianLima** [comment]
Go into this page: https://github.com/BrianLima/UWPHook/releases
Download "release.zip" 
unzip it and place all the files in a folder on your pc
Run UWPHook.exe

No need to apoligize :D

**Comment by cybnz** [comment]
Thanks so much.  Somehow I missed that!  Looks great by the way.

**Comment by cybnz** [comment]
Update: The original zip didn't have the exe, must be an error when downloading.  Or most likely I deleted it on accident.
