### ISSUE TITLE
Sea of Thieves - Value does not fall within the expected range.

### ISSUE THREAD

**Issue by Cryogenetica** [BrianLima/UWPHook#24]
When attempting to launch Sea of Thieves I get the following error message.

Error while trying to launch your app. Value does not fall within the expected range.

**Comment by BrianLima** [comment]
Hi, could you post a print of the error happening, and right click the shortcut on Steam and print that too? If possible, could you post the text in the 'Target' field? This way i can understand it better. I must have messed something in the last update.

**Comment by Cryogenetica** [comment]
Hi Brian,

Screenshots as requested 

https://imgur.com/a/bHBSXxn

Just as an aside, using the below string as a launch condition for explorer.exe yields a successful launch.

shell:appsFolder\Microsoft.SeaofThieves_8wekyb3d8bbwe!AthenaClientShipping

**Comment by BrianLima** [comment]
Yeah, i messed up, i'm going to fix it, thanks to the report!

**Comment by BrianLima** [comment]
Fixed with https://github.com/BrianLima/UWPHook/releases/tag/2.5.1
