### ISSUE TITLE
[Feature Request] changing system language before launching game.

### ISSUE THREAD

**Issue by dominikpflegerl** [BrianLima/UWPHook#3]
Hey,

Would it be possible to add a feature, which changes the system language to english -> launching the game -> change back to previous system langauge.

problem is that I use a german version of windows I'm one who plays every single game in english, but UWP games won't let me to do that.  I always have to change the language to english - start the game - change back to german, which is a bit annoying.

**Comment by BrianLima** [comment]
I highly doubt it would be possible, but i might look towards adding launch options to UWPHook.

Do you change what on your system? Keyboard layout, Region, or just Windows display language? The later might be possible with Intlcfg.

**Comment by AbGedreht** [comment]
It's the display language.

**Comment by BrianLima** [comment]
All right, thanks, i'll investigate further and try to implement this.

**Comment by Alia5** [comment]
You also, don't have to relog into windows for the UWP-Apps to change their language. Only if you really want to change language of the whole operating system.

So basically: Change display language -> wait until game closes -> change back.

**Comment by AbGedreht** [comment]
Yes, I know. I'm already doing this steps but it's a little bit annoying to do this every single time.
I created a little PowerShell script

`Set-WinUILanguageOverride en-US`
`Start-Process explorer.exe shell:AppsFolder\Microsoft.OpusPG_8wekyb3d8bbwe!OpusReleaseFinal`
`Start-Sleep -s 30`
`Set-WinUILanguageOverride de-AT`
`pause`

works fine.

**Comment by BrianLima** [comment]
Does the culture language have to be installed in order to this script to work? I'm working on a implementation right now.

**Comment by AbGedreht** [comment]
Yes, I tried several languages and still got my default language in FH3.

In my settings german and english is listed, and "de-DE, de-AT, en-US, en-GB" work flawless, "fr-fr" "es-ES" didn't change anything.

**Comment by BrianLima** [comment]
It's funny, I implemented this and i'm debugging on my main gamming PC, it's totally in English, buth ui and culture language, but my game always start as pt-BR, even when UWPHook runs the script to set it on en-US. I heard people saying that the game's language is tied to the region you bought it, so maybe that's the case?

**Comment by BrianLima** [comment]
Maybe some regions have limited language support too, seems inconsistent.

**Comment by AbGedreht** [comment]
Well, I bought it on the us store and can play it with german and english language. I'll try some other languages later. Store page showed me all available languages for the game.

**Comment by BrianLima** [comment]
I implemented this, but as i said, i see no change when i play either Forza Horizon 3 or Halo 5 Forge, but i will still leave the option there because it will be useful to you, this feature will be on the next release, should hit no later than this weekend.

**Comment by AbGedreht** [comment]
Well, after you released 2.1.4 I was able to add the games (FH3 and FM6) to Steam with en-US language and it works for me, altough I would suggest to change the behaviour of the language change. Problem is, that after I close the game language is still set to en-US. Maybe like my little PowerShell script?

**Comment by BrianLima** [comment]
Might be a bug causing it to not change the language back, I tried to store the current system language before trying to change it. I will do some more tests to find out what is happening.

**Comment by kitzik** [comment]
Forza Horizon 3 language is tied to system date/time formats, not to the language

**Comment by penderes** [comment]
Thing is, it works for Forza Horizon 4 (probably 3 as well), but it will not change the language back after launching the game :(
