### ISSUE TITLE
[Feature Request] UWPHook Portable executable

### ISSUE THREAD

**Issue by Forceflow** [BrianLima/UWPHook#35]
Hey there,

I'm the guy who asked you on Twitter for a portable version of UWPHook, which you provided, which is great! Thanks again! Any chance we might see regular portable UWPHook releases in the future as well? Just the executable without the installer wrapped around it.

I like to keep a lot of the tools I need on several systems in a folder I can just plop down and start working with. UWPHook would be an excellent candidate for that.

**Comment by SoulRepo** [comment]
I'll try to make a ZIP.
