### ISSUE TITLE
[Feature] Add custom steam grid images for imported games.

### ISSUE THREAD

**Issue by BrianLima** [BrianLima/UWPHook#4]
So, with the new app this might be possible, using it together with a web site that provides Steam grid images for games, the problem is: I can't figure out how does Steam generates the id it uses to tie non-steam games with their images on /config/grid.

**Comment by BrianLima** [comment]
It seems that Steam uses a CRC hash generated from the path to the exe and game name, i'll look further this weekend and try to understand this better.

**Comment by NazmusLabs** [comment]
@BrianLima yes, you are correct; however, that's only by default. You can tell steam to use a custom image. The following is an example of Minecraft UPW with a custom image.

![Uploading Steam with MinecraftUWP added using UPWHook and Custom Image.png…]()
