### ISSUE TITLE
Unable to open steam chat/overlay?

### ISSUE THREAD

**Issue by MrJSec** [BrianLima/UWPHook#40]
Hi,

First time user of UWPHook, using UWPHook with Microsoft games the games load fine and show that I'm playing the game "In non-Steam game Gears Of War 5" but I'm unable to open the steam chat, I have tried the following:

Changed Key combo (Default is Tab + Shift).
Ran Steam as admin.

I'm wording if this is normal or if I have done something wrong on my side?

Thanks!

**Comment by BrianLima** [comment]
Steam overlay is not supported.
