### ISSUE TITLE
Can't find Dead Cells

### ISSUE THREAD

**Issue by Ansem93** [BrianLima/UWPHook#46]
Hi, I have installed Dead Cells throught game pass. 
All the other 5 games I have installed are correctly detected. 
Only Dead Cells can't be found :(

How can I find it? I really can't find it even in the unrecognized apps

**Comment by BrianLima** [comment]
Hey, Dead Cells is correctly listed as follows:
![image](https://user-images.githubusercontent.com/1337383/95652705-64285080-0ac9-11eb-903b-dec31ba766ed.png)

**Comment by Ansem93** [comment]
THanks, I totally misseed it :(

**Comment by BrianLima** [comment]
No problem! Closing this issue.
