### ISSUE TITLE
Astroneer doesnt appear

### ISSUE THREAD

**Issue by FVQxH05TILE** [BrianLima/UWPHook#57]
Please can someone help

**Comment by BrianLima** [comment]
It's listed as `SystemEraSoftworks.29415440E1269_ftk5pbg2rayv2!ASTRONEER`

![image](https://user-images.githubusercontent.com/1337383/109392774-ba712100-78fc-11eb-80a5-397143e6f1ae.png)

**Comment by jmb496** [comment]
Just downloaded the latest version and not seeing Astroneer.  Noticed similar comments on Reddit with no response so trying here.  I also own the game on Steam so I don't know if it would be hidden because of that.
