### ISSUE TITLE
Forza Motorsport 6: Apex not in list of installed apps

### ISSUE THREAD

**Issue by Dougal19** [BrianLima/UWPHook#6]

**Comment by BrianLima** [comment]
Could you please run this script  https://github.com/BrianLima/UWPHook/blob/master/UWPHook/Resources/GetAUMIDScript.txt and paste the result here or on pastebin?

**Comment by Dougal19** [comment]
Sure, how exactly do I run it?

**Comment by BrianLima** [comment]
Forgot to mention you have to run it on Powershell.

**Comment by Dougal19** [comment]
I'm having trouble getting the script to run. This is the output in Powershell:

`PS C:\Users\dougo\Downloads> C:\Users\dougo\Downloads\script.ps1
?$installedapps : The term '?$installedapps' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\dougo\Downloads\script.ps1:1 char:1
+ ?$installedapps = get-AppxPackage
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (?$installedapps:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 `

**Comment by BrianLima** [comment]
Try pasting the script directly into the powershell command console, for me it works this way.

**Comment by Dougal19** [comment]
Thanks, I got it working. The line referring to Forza Apex seems to be

`ms-resource:Title  |  Microsoft.ApexPG_8wekyb3d8bbwe!forzamotorsportapex;
`

**Comment by BrianLima** [comment]
Does the entry for Apex change if run this script? 
`$installedapps = get-AppxPackage

$aumidList = @()
foreach ($app in $installedapps)
{
    try {
        foreach ($appx in (Get-AppxPackageManifest $app))
        {
            
            $aumidList += $appx.Package.Properties.DisplayName + "  |  "+ 
            $app.packagefamilyname + "!" + $appx.package.applications.application.id + ";"
            
        }
    } catch {
        $ErrorMessage = $_.Exception.Message
        $FailedItem = $_.Exception.ItemName
    }
}

$aumidList;`

I don't have Apex installed right now and will take 6 hours to download it, I can't believe Microsoft didn't fill the appxPackageInfo properly for it.

**Comment by Dougal19** [comment]
That brought up this. If that's no use don't worry about downloading Apex to sort it out.
`Forza Motorsport 6: Apex  |  Microsoft.ApexPG_8wekyb3d8bbwe!forzamotorsportapex;`

**Comment by BrianLima** [comment]
Good to know, thanks, publishing the fix now. Will be live in some minutes on version 2.1.4

**Comment by BrianLima** [comment]
Fixed https://github.com/BrianLima/UWPHook/releases/tag/2.1.4

**Comment by Dougal19** [comment]
Brilliant, thanks for the help.
