### ISSUE TITLE
Out of Memory Exception

### ISSUE THREAD

**Issue by carnageX** [BrianLima/UWPHook#7]
Getting an Out of Memory exception when trying to export my games. 

![image](https://cloud.githubusercontent.com/assets/7111043/19335174/cd3adc90-90c6-11e6-9be6-79ed808735e6.png)

The game's I'm trying to add to Steam are Forza Horizon 3 and Halo 5: Forge.  Tried just FH3, and it still crashes (the OoM exception pops up 4 times when I try and export).  Tried with both Steam open and closed while exporting.

**Comment by carnageX** [comment]
Ok, looks like it's just FH3 having issues being added.  Halo 5: Forge added fine.

**Comment by TheloniousDotFunk** [comment]
I as well am having the issue adding Forza Horizon 3 and receive the same error message. I don't have other Windows10 games to attempt but based on the your post carnageX it sounds like it's isolated to FH3.

**Comment by BrianLima** [comment]
It's a problem when it is trying to find what image use as logo, i'm investigating.

**Comment by BrianLima** [comment]
Some live tile images found on Forza Horizon 3 directory seems to have a invalid file format, writing the fix now.

**Comment by BrianLima** [comment]
Fixed now on 2.2.1.

**Comment by TheloniousDotFunk** [comment]
Can confirm this is fixed and working now as of 2.2.1.

Thank you so much @BrianLima for the continued updates and support! <3

**Comment by BrianLima** [comment]
@TheloniousDotFunk You're welcome :D

I'm glad you guys like my tool.

**Comment by carnageX** [comment]
Fantastic - confirmed fixed for me as well.  

From one developer to another, thanks for the updates, appreciate it!
