### ISSUE TITLE
more of a question then a issue i suppose

### ISSUE THREAD

**Issue by comatossa** [BrianLima/UWPHook#88]
hello it would be easy for me to just explain um i added a hirman 3 as non steam game using uwp for the sole purpose of being able to use steams controller customizing stuff like trigger sens and what not and i noticed when i make a controller config for hirman 3 and launch it the game doesn't use the config at all and just uses the default bindings. sorry if this was already asked at some point im sleep deprived at the moment if you need more info just ask

**Comment by BrianLima** [comment]
Hi, UWPHook does not enables steam's input in a game unfortunately.
