### ISSUE TITLE
MSFS 2020 Infinite loop

### ISSUE THREAD

**Issue by stevealexandre** [BrianLima/UWPHook#93]
Hello dude,

Unfortunately, the game created on steam does not working with MSFS2020.
When I create the game via UWPHook, he try to start the exe "gamelaunchhelper.exe" from the MSFS content directory where the exe of MSFS is.
My steam is displayed at "playing on Microsoft Flight Simulator" but the game is not starting.
When look into the process manager, I can see the gamelaunchhelper process is created every second with a new PID and the only way to stop and being not show playing anymore on steam it is to close the windows/restart the computer.

See below more details on images :
- Process loop with new PID :
![Process loop](https://i.imgur.com/764N2cR.gif)

- gamelaunchhelper.exe of process info :
![Exe info](https://i.imgur.com/DZ51EkC.png)

- MSFS Directory with the gamelaunchhelper.exe and the MSFS exe
![MSFS Directory](https://i.imgur.com/2lEUeAE.png)

Any fix would be really great to let my friends now I'm playing on it while they are playing on their side via the steam game version.

Thank you for your time.

**Comment by novemberdobby** [comment]
I've noticed this too on games that used to work (e.g. FAR: Changing Tides). May be the same root cause as #92.

You can break the loop by running: `taskkill /F /IM gamelaunchhelper.exe`

Running UWPHook from Visual Studio works, but not from Steam. I tried a workaround where UWPHook runs GameLaunchHelper.exe directly, or the app exe itself, but neither would actually open the game. 🤔

**Comment by stevealexandre** [comment]
I have found the way to stop the loop process by launching the game as usual via his own icon.
I've seen #92 and tried with admin permissions etc... but nothing was working.
As I understand, not all games are launched via gamelaunchhelper and it's a pain. Maybe it's a "protection" from microsoft to deny apps like uwphook.

**Comment by novemberdobby** [comment]
We could get around this in UWPHook by launching:
`explorer shell:appsFolder\CoffeeStainStudios.DeepRockGalactic_496a1srhmar9w!AppDeepRockGalacticShipping`

This breaks the tracking, which could _maybe_ be fixed by checking for the existence of `FSD-WinGDK-Shipping.exe` (for the example above) in the process list.

**Comment by stevealexandre** [comment]
I'm currently working on a fix.
Being able to start MFS 2020 and have my playing status with the game launched successfully.
I'm doing some crosschecking of my fix because instead of checking parent/children pid, I'm looking at the executable name by getting it from parsing the argument.

Microsoft.FlightSimulator_8wekyb3d8bbwe!App => Parse to have "FlightSimulator" => look for "FlightSimulator.exe" in process list => yes => display running on steam.

I have truncate the argument with substring to truncate the left of "." and right of "_" BUT because it will not be fun anyway, for example forza have not the same string base 😒 (Microsoft.624F8B84B80_8wekyb3d8bbwe!Forzahorizon5) so parsing will not give the correct value and will not being able to detect the process (got 624F8B84B80.exe). Looking for a better implementation but guys, we are closed to a fix. ✌

Will do a PR when ready and I suggest of course at mid time to refactor my code and doing something better at the end because I'm not a dev, just an integrator in my job so it's look more like a hack. 😅

**Comment by novemberdobby** [comment]
`GetAUMIDScript.ps1` could be modified to provide the install path (`$app.InstallLocation`)

Then `install_path\MicrosoftGame.config` contains the correct exe name (at xpath `/Game/ExecutableList/Executable/@Name`)

This works for Far: Changing Tides (`FarChangingTides.exe`) and Deep Rock Galactic (`FSD\Binaries\WinGDK\FSD-WinGDK-Shipping.exe`), is it the same for Forza?

**Comment by stevealexandre** [comment]
> `GetAUMIDScript.ps1` could be modified to provide the install path (`$app.InstallLocation`)
> 
> Then `install_path\MicrosoftGame.config` contains the correct exe name (at xpath `/Game/ExecutableList/Executable/@Name`)
> 
> This works for Far: Changing Tides (`FarChangingTides.exe`) and Deep Rock Galactic (`FSD\Binaries\WinGDK\FSD-WinGDK-Shipping.exe`), is it the same for Forza?

Thanks for the tips. Could be the trick. I'm working on it to do the PR asap if possible tonight.
Working for Forza5 but found a game which have a different way again to start => Halo Master Chief Collection. It start mcclauncher.exe with the argument "MCC\Binaries\Win64\MCCWinStore-Win64-Shipping.exe" which will be the end exe to be running. Will have to parse it too and imho, there is few games which will need some exception to catch them running.

**Comment by stevealexandre** [comment]
Logic is implemented.
Doing some cross testing with differents games to confirm most of game are detected.

**Comment by stevealexandre** [comment]
Results of the cross tests :

- [✔] - MFS2020 
- [✔] - Forza 5 
- [❌] - Halo master chief edition > The process doesn't have path (weird launcher, working on a workarround for some of this)
- [✔] - Myst
- [✔] - Farming Simulator 22
- [✔] - Train Sim World 3

Should be able to have the final fix for tomorrow to handle MCC launcher like usecases. 🤞

**Comment by stevealexandre** [comment]
PR is created since the fix is now working on all game above listed so should be work on every games.
Waiting now the merge and the final build of the release to let you enjoy running game through steam and being displayed as playing ✌

**Comment by BrianLima** [comment]
Great, thanks for the contribution, i'll be reviewing it tomorrow, ok?

**Comment by stevealexandre** [comment]
No problem :).

**Comment by stevealexandre** [comment]
Closing the issue following the PR merged.
